### ISSUE TITLE
empty list

### ISSUE THREAD

**Issue by Mouvedia** [eecollante10/LightTable-functions-list#1]
OS: Mac OS X
version: 0.8.1

The list is empty.
I have functions declared in my .js file.

**Comment by eecollante10** [comment]
The functions are added if the function declaration starts at the beginning of the line.
So:

``` javascript
function foo(){
} 
```

gets added and:

``` javascript
     function foo(){
}
```

does not, since the plugin uses the following regular expression to find the functions: ["^function"](https://github.com/eecollante10/LightTable-functions-list/blob/master/src/lt/plugins/functions_list.cljs#L23)

Let me know if you think that should be changed to allow cases like the second one above, or if you propose other changes

**Comment by Mouvedia** [comment]
You should probably skip whitespace: it could easily be mistaken for a bug.

**Comment by eecollante10** [comment]
I've updated it, and you can download the update from Light Table

**Comment by Mouvedia** [comment]
It seems to be working, thanks.

**Comment by Mouvedia** [comment]
@eecollante10 there are unnecessary spaces added before the keyword `function`—and sometimes after. It's pretty minor but looks amateurish.

It's related to the length and the panel's available width.

**Comment by Mouvedia** [comment]
@eecollante10 there are unnecessary spaces added before the keyword `function`—and sometimes after. It's pretty minor but looks amateurish.

It's related to the character length and the panel's available width: you should probably only list the names of the functions.
